volumes:
  css-sprites-app-sync: { external: true }
  bundle: { driver: local }
  config: { driver: local }
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - css-sprites-app-sync:/app:nocopy
      - bundle:/bundle
      - config:/config
    networks:
      default:
        aliases:
          - css-sprites
